# Generated by Django 4.2.5 on 2024-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mblnumber', models.IntegerField()),
                ('futsal_choice', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
